### ISSUE TITLE
Reset button issue on Admin side

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#1]
No data comes on clicking on Pending restaurants, data onlyc omes after clicking on Reset button
![reset button data](https://cloud.githubusercontent.com/assets/10379746/8144128/3f32ef4c-11eb-11e5-975c-cba88c31028f.JPG)

**Comment by sattastudd** [comment]
Add delivery area link should be there
![delivery area link](https://cloud.githubusercontent.com/assets/10379746/8144139/b68b7870-11eb-11e5-84d4-2e7fce3f3e11.JPG)

**Comment by sattastudd** [comment]
Add cuisines link should be there while selecting cuisines, after adding the cuisines should appear in the filter block.
change button name to save cuisines
![cuisines add](https://cloud.githubusercontent.com/assets/10379746/8144154/0d88f12a-11ec-11e5-8b80-b9f48bf682a9.JPG)

**Comment by sattastudd** [comment]
Dish type? need to discussed.
Radio button should be for Non veg.
half price input field should be before full price input.
once category item added it should come in tabular form.
edit and delete icon should be there along with every dish and category name to delete or edit dish or category.
Save delivery area button should be renamed to save menu details.
![menu page](https://cloud.githubusercontent.com/assets/10379746/8144174/a6f28eca-11ec-11e5-821e-530c5285b84a.JPG)

**Comment by grvtiwari** [comment]
Open a new issue for each issue.
Comments would be used for discussion on the issue. :P

**Comment by sattastudd** [comment]
Okay my bad :P

**Comment by grvtiwari** [comment]
Closed. Needed a DF.
