### ISSUE TITLE
New Dishes not coming in search value

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#10]
New dish added in Restaurant, but that Dish is not coming in search value.
![new dish](https://cloud.githubusercontent.com/assets/10379746/8290725/745fc948-1942-11e5-94c2-d22ec89ceb48.JPG)
![search value](https://cloud.githubusercontent.com/assets/10379746/8290728/789f26c0-1942-11e5-8772-47720cb0d79a.JPG)

**Comment by sattastudd** [comment]
chicken masala not coming in search value

**Comment by grvtiwari** [comment]
That's a bug. I know. :P

It will be fixed in next commit.
We are maintaining a separate collection for dishes.
And that collection is not updated after any updated.

Will be fixed in next commit.

**Comment by grvtiwari** [comment]
Fixed in 1029c59a10ccce2952147c27fcaa45fbf927fe5b.
