### ISSUE TITLE
Menu Field invisible

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#15]
No category fieldcoming to insert menu for restaurants in Admin page.
![menu field invisible](https://cloud.githubusercontent.com/assets/10379746/8382654/c3ddb874-1c51-11e5-93d9-ac29848e51f3.JPG)

**Comment by grvtiwari** [comment]
Issue fixed in 4d71f0e19b0282dce714bb0caec121f25f1387ce.
