### ISSUE TITLE
Add cuisines link should be there while selecting cuisines

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#3]
Add cuisines link should be there while selecting cuisines, after adding the cuisines should appear in the filter block.
change button name to save cuisines
![cuisines add](https://cloud.githubusercontent.com/assets/10379746/8147732/9b9a1064-1298-11e5-93d8-15b2dddb7bdb.JPG)

**Comment by grvtiwari** [comment]
Fixed in 081958338309c34291ae11c13d6cf175cedf5284
