### ISSUE TITLE
Adding menu page

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#4]
Dish type? need to discussed.
Radio button should be for Non veg.
half price input field should be before full price input.
once category item added it should come in tabular form.
edit and delete icon should be there along with every dish and category name to delete or edit dish or category.
Save delivery area button should be renamed to save menu details.

**Comment by grvtiwari** [comment]
Closed in b8082d5c7894aa45cbfe84da868a8898ca0602bb
