### ISSUE TITLE
Search field Syndrome

### ISSUE THREAD

**Issue by sattastudd** [sattastudd/KhanaShana#6]
1. By clicking on 'search by location', a modal should appear with all the localities listed in the city. Clicking on the locality will take the user to Search page where all the Restaurant serve in that locality should appear.

2 After typing, the pre-dropdown should hide and when the the typed words are deleted the pre-dropdown should come back.

3. Nice differentiation should be there between results of restaurants and dishes.
![search field](https://cloud.githubusercontent.com/assets/10379746/8147795/a6bcff9a-129a-11e5-8f45-7c9db8f14337.JPG)

**Comment by grvtiwari** [comment]
It is same as the issue reported for homepage.
Closed in [commit].(https://github.com/sattastudd/KhanaShana/commit/f1b3119fef8fc92f062d3a2c478d7f72cfdda43f)

**Comment by sattastudd** [comment]
nailed it

**Comment by sattastudd** [comment]
chha gaye launde tum to
